# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'punto4_calcular_resistencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(567, 433)
        Dialog.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 40, 241, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 131, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(360, 130, 131, 31))
        self.label_3.setObjectName("label_3")
        self.temperatura = QtWidgets.QTextEdit(Dialog)
        self.temperatura.setGeometry(QtCore.QRect(40, 180, 151, 31))
        self.temperatura.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.temperatura.setObjectName("temperatura")
        self.resistencia = QtWidgets.QTextEdit(Dialog)
        self.resistencia.setGeometry(QtCore.QRect(350, 180, 151, 31))
        self.resistencia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.resistencia.setObjectName("resistencia")
        self.boton_ejecutar = QtWidgets.QPushButton(Dialog)
        self.boton_ejecutar.setGeometry(QtCore.QRect(370, 320, 121, 31))
        self.boton_ejecutar.setStyleSheet("background-color: rgb(53, 88, 243);")
        self.boton_ejecutar.setObjectName("boton_ejecutar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">calculo resistencia PT100</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">VALOR TEMPERATURA</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">VALOR RESISTENCIA</p></body></html>"))
        self.boton_ejecutar.setText(_translate("Dialog", "EXECUTE"))
    def ejecutar(self):
        R0 = 100  # Valor de resistencia a una temperatura de referencia (en ohmios)
        a = 3.9083e-3  # Coeficiente a de la ecuación de Steinhart-Hart
        b = -5.775e-7  # Coeficiente b de la ecuación de Steinhart-Hart
        c = -4.183e-12  # Coeficiente c de la ecuación de Steinhart-Hart

        temperatura_usuario = float(self.temperatura.toPlainText())

        if 0 <= temperatura_usuario <= 750:
            # Ecuación para temperaturas positivas
            R = R0 * (1 + a * temperatura_usuario + b * temperatura_usuario**2)
        elif -200 <= temperatura_usuario < 0:
            # Ecuación para temperaturas negativas
            R = R0 * (1 + a * temperatura_usuario + b * temperatura_usuario**2 + c * (temperatura_usuario - 100) * (temperatura_usuario**3))
        else:
            self.resistencia.setText('La temperatura ingresada está fuera del rango permitido.')
        valor_resistencia = str(R)
        self.resistencia.setText(valor_resistencia)
        #print(f'La resistencia calculada es: {R} ohmios')
        

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.boton_ejecutar.clicked.connect(ui.ejecutar)
    Dialog.show()
    sys.exit(app.exec_())
