# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'punto3_coordenadas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from funciones_coordenadas import Conversion
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(679, 393)
        Dialog.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 10, 261, 71))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(290, 130, 121, 31))
        self.label_3.setObjectName("label_3")
        self.coordenada_rectangular_x = QtWidgets.QTextEdit(Dialog)
        self.coordenada_rectangular_x.setGeometry(QtCore.QRect(20, 200, 41, 31))
        self.coordenada_rectangular_x.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.coordenada_rectangular_x.setObjectName("coordenada_rectangular_x")
        self.coordenada_cilindrica_x = QtWidgets.QTextEdit(Dialog)
        self.coordenada_cilindrica_x.setGeometry(QtCore.QRect(270, 200, 41, 31))
        self.coordenada_cilindrica_x.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.coordenada_cilindrica_x.setObjectName("coordenada_cilindrica_x")
        self.boton_ejecutar = QtWidgets.QPushButton(Dialog)
        self.boton_ejecutar.setGeometry(QtCore.QRect(530, 310, 101, 41))
        self.boton_ejecutar.setStyleSheet("background-color: rgb(82, 105, 255);")
        self.boton_ejecutar.setObjectName("boton_ejecutar")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(500, 130, 121, 31))
        self.label_4.setObjectName("label_4")
        self.coordenada_esferica_x = QtWidgets.QTextEdit(Dialog)
        self.coordenada_esferica_x.setGeometry(QtCore.QRect(480, 200, 41, 31))
        self.coordenada_esferica_x.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.coordenada_esferica_x.setObjectName("coordenada_esferica_x")
        self.coordenada_rectangular_y = QtWidgets.QTextEdit(Dialog)
        self.coordenada_rectangular_y.setGeometry(QtCore.QRect(80, 200, 41, 31))
        self.coordenada_rectangular_y.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.coordenada_rectangular_y.setObjectName("coordenada_rectangular_y")
        self.coordenada_rectangular_z = QtWidgets.QTextEdit(Dialog)
        self.coordenada_rectangular_z.setGeometry(QtCore.QRect(140, 200, 41, 31))
        self.coordenada_rectangular_z.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.coordenada_rectangular_z.setObjectName("coordenada_rectangular_z")
        self.coordenada_cilindrica_y = QtWidgets.QTextEdit(Dialog)
        self.coordenada_cilindrica_y.setGeometry(QtCore.QRect(330, 200, 41, 31))
        self.coordenada_cilindrica_y.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.coordenada_cilindrica_y.setObjectName("coordenada_cilindrica_y")
        self.coordenada_cilindrica_z = QtWidgets.QTextEdit(Dialog)
        self.coordenada_cilindrica_z.setGeometry(QtCore.QRect(390, 200, 41, 31))
        self.coordenada_cilindrica_z.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.coordenada_cilindrica_z.setObjectName("coordenada_cilindrica_z")
        self.coordenada_esferica_y = QtWidgets.QTextEdit(Dialog)
        self.coordenada_esferica_y.setGeometry(QtCore.QRect(540, 200, 41, 31))
        self.coordenada_esferica_y.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.coordenada_esferica_y.setObjectName("coordenada_esferica_y")
        self.coordenada_esferica_z = QtWidgets.QTextEdit(Dialog)
        self.coordenada_esferica_z.setGeometry(QtCore.QRect(600, 200, 41, 31))
        self.coordenada_esferica_z.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.coordenada_esferica_z.setObjectName("coordenada_esferica_z")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">convercion de coordenadas</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "coordenada rectangular"))
        self.label_3.setText(_translate("Dialog", "coordenada cilindrica"))
        self.boton_ejecutar.setText(_translate("Dialog", "EXECUTE"))
        self.label_4.setText(_translate("Dialog", "coordenada esferica"))
    def conversion_coordenadas(self):

        conversion = Conversion()
        x = float(self.coordenada_rectangular_x.toPlainText())
        y = float(self.coordenada_rectangular_y.toPlainText())
        z = float(self.coordenada_rectangular_z.toPlainText())
        
        coordenadas_cilindricas = Conversion.cartesiana_a_cilindrica(x,y,z)
        coordenadas_esfericas = Conversion.cartesina_a_esferica(x,y,z)
        esferica_x = str(coordenadas_esfericas[0] )
        esferica_y = str(coordenadas_esfericas[1])
        esferica_z = str(coordenadas_esfericas[2])
        
        cilindrica_x = str(coordenadas_cilindricas[0])
        cilindrica_y = str(coordenadas_cilindricas[1])
        cilindrica_z = str(coordenadas_cilindricas[2])
        
        self.coordenada_cilindrica_x.setText(cilindrica_x)
        self.coordenada_cilindrica_y.setText(cilindrica_y)
        self.coordenada_cilindrica_z.setText(cilindrica_z)
        
        self.coordenada_esferica_x.setText(esferica_x)
        self.coordenada_esferica_y.setText(esferica_y)
        self.coordenada_esferica_z.setText(esferica_z)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.boton_ejecutar.clicked.connect(ui.conversion_coordenadas)
    Dialog.show()
    sys.exit(app.exec_())
