# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'punto5_matriz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import numpy as np
from punto5_matriz_operaciones import AngulosMatriz
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(688, 468)
        Dialog.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"background-color: rgb(255, 69, 72);")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(240, 30, 211, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 100, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 81, 21))
        self.label_3.setObjectName("label_3")
        self.angulox = QtWidgets.QTextEdit(Dialog)
        self.angulox.setGeometry(QtCore.QRect(160, 100, 231, 31))
        self.angulox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.angulox.setObjectName("angulox")
        self.anguloy = QtWidgets.QTextEdit(Dialog)
        self.anguloy.setGeometry(QtCore.QRect(160, 160, 231, 31))
        self.anguloy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.anguloy.setObjectName("anguloy")
        self.anguloz = QtWidgets.QTextEdit(Dialog)
        self.anguloz.setGeometry(QtCore.QRect(160, 220, 231, 31))
        self.anguloz.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.anguloz.setObjectName("anguloz")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 320, 111, 21))
        self.label_4.setObjectName("label_4")
        self.matriz_total = QtWidgets.QTextEdit(Dialog)
        self.matriz_total.setGeometry(QtCore.QRect(160, 320, 231, 121))
        self.matriz_total.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.matriz_total.setObjectName("matriz_total")
        self.boton_ejecutar = QtWidgets.QPushButton(Dialog)
        self.boton_ejecutar.setGeometry(QtCore.QRect(520, 340, 131, 41))
        self.boton_ejecutar.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.boton_ejecutar.setObjectName("boton_ejecutar")
        
        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">MATRIZ DE ROTACION</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">ANGULO X</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">ANGULO Y</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">ANGULO Z</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">MATRIZ TOTAL</span></p></body></html>"))
        self.boton_ejecutar.setText(_translate("Dialog", "CALCULAR"))
        #self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">OPERACION</span></p></body></html>"))
        

    def ejecucion(self):
        
        angulosMatriz = AngulosMatriz
        valorx = float(self.angulox.toPlainText())
        valory = float(self.angulox.toPlainText())
        valorz = float(self.angulox.toPlainText())
        resultado_matrizx = AngulosMatriz.angulox(valorx)
        resultado_matrizy = AngulosMatriz.anguloz(valory)
        resultado_matrizz = AngulosMatriz.anguloy(valorz)
        
        matriz_total = str(np.dot(resultado_matrizz, np.dot(resultado_matrizx,resultado_matrizy)))
        #print(matriz_total)
        self.matriz_total.setText(matriz_total)

        
        
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.boton_ejecutar.clicked.connect(ui.ejecucion)
    Dialog.show()
    sys.exit(app.exec_())
